# Generated by Django 3.2.2 on 2021-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('numeros', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
