# Generated by Django 3.2.2 on 2021-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
