# Generated by Django 3.2.2 on 2021-11-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefonos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
