# Generated by Django 3.2.2 on 2021-11-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreMi', '0002_alter_sobremi_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremi',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sobremi',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
