# Generated by Django 3.2.2 on 2021-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreMi', '0003_auto_20211105_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremi',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
    ]
