# Generated by Django 3.2.2 on 2021-11-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desarrollos',
            new_name='Desarrollo',
        ),
    ]
